# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Project/mfcc/project_1/project_1.srcs/sources_1/ip/fil_ram/fil_ram.xci
# IP: The module: 'fil_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/mfcc/project_1/project_1.srcs/sources_1/ip/fil_ram/fil_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fil_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/Project/mfcc/project_1/project_1.srcs/sources_1/ip/fil_ram/fil_ram.xci
# IP: The module: 'fil_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/mfcc/project_1/project_1.srcs/sources_1/ip/fil_ram/fil_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fil_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
