# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Project/mfcc/project_1/project_1.srcs/sources_1/ip/mult/mult.xci
# IP: The module: 'mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/mfcc/project_1/project_1.srcs/sources_1/ip/mult/mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/Project/mfcc/project_1/project_1.srcs/sources_1/ip/mult/mult.xci
# IP: The module: 'mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Project/mfcc/project_1/project_1.srcs/sources_1/ip/mult/mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
